import { useState, useEffect, useCallback } from 'react';
import { Download, RefreshCw, FileArchive, Clock, Play, Trash2, Database, RotateCcw, Calendar, Settings, CheckCircle, XCircle, Loader } from 'lucide-react';
import {Layout} from '@/components/Layout';
// ─── Fake Data ───────────────────────────────────────────────────────────────
const FAKE_BACKUPS = [
  {
    id: 1,
    filename: 'backup_2025_04_29_02_00_00.sql',
    size: '14,302 KB',
    created_at: '2025-04-29 02:00:00',
    status: 'completed',
    db_type: 'postgresql',
  },
  {
    id: 2,
    filename: 'backup_2025_04_28_02_00_00.sql',
    size: '14,189 KB',
    created_at: '2025-04-28 02:00:00',
    status: 'completed',
    db_type: 'postgresql',
  },
  {
    id: 3,
    filename: 'backup_2025_04_27_02_00_01.sql',
    size: '13,944 KB',
    created_at: '2025-04-27 02:00:01',
    status: 'completed',
    db_type: 'postgresql',
  },
  {
    id: 4,
    filename: 'backup_2025_04_26_02_00_00.sql',
    size: '13,801 KB',
    created_at: '2025-04-26 02:00:00',
    status: 'completed',
    db_type: 'postgresql',
  },
  {
    id: 5,
    filename: 'backup_2025_04_25_02_00_03.sql',
    size: '13,620 KB',
    created_at: '2025-04-25 02:00:03',
    status: 'completed',
    db_type: 'postgresql',
  },
  {
    id: 6,
    filename: 'backup_2025_04_24_02_00_00.sql',
    size: '0 KB',
    created_at: '2025-04-24 02:00:00',
    status: 'failed',
    db_type: 'postgresql',
  },
];

// ─── Fake SQL content for download ───────────────────────────────────────────
const generateFakeSql = (filename) => `-- PostgreSQL dump
-- Generated by pg_dump version 15.3
-- Filename: ${filename}
-- Date: ${new Date().toISOString()}

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Name: users; Type: TABLE; Schema: public
--

CREATE TABLE IF NOT EXISTS public.users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

INSERT INTO public.users (name, email, created_at) VALUES
  ('Alice Johnson', 'alice@example.com', '2024-01-10 09:15:00'),
  ('Bob Smith', 'bob@example.com', '2024-01-12 11:30:00'),
  ('Carol White', 'carol@example.com', '2024-01-15 14:45:00'),
  ('David Brown', 'david@example.com', '2024-02-01 08:00:00');

--
-- Name: orders; Type: TABLE; Schema: public
--

CREATE TABLE IF NOT EXISTS public.orders (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES public.users(id),
    total NUMERIC(10,2) NOT NULL,
    status VARCHAR(50) DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT NOW()
);

INSERT INTO public.orders (user_id, total, status, created_at) VALUES
  (1, 149.99, 'completed', '2024-02-10 10:00:00'),
  (2, 89.50,  'completed', '2024-02-11 12:30:00'),
  (3, 210.00, 'pending',   '2024-02-12 09:45:00'),
  (4, 55.75,  'failed',    '2024-02-13 16:00:00');

-- End of dump
`;

// ─── Helpers ──────────────────────────────────────────────────────────────────
const DAYS = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const DAYS_SHORT = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];

const dbTypeConfig = {
  postgresql: { label: 'PostgreSQL', pill: 'bg-blue-100 text-blue-700 border-blue-200' },
  mysql:      { label: 'MySQL',      pill: 'bg-orange-100 text-orange-700 border-orange-200' },
  sqlite:     { label: 'SQLite',     pill: 'bg-emerald-100 text-emerald-700 border-emerald-200' },
};

const getNextRunText = (s) => {
  if (!s.enabled) return 'Disabled';
  const [h, m] = s.time.split(':').map(Number);
  const now = new Date();
  const next = new Date();
  if (s.frequency === 'hourly') {
    const n = new Date(now.getTime() + 3600000);
    return `in ~1 hour (${n.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })})`;
  }
  next.setHours(h, m, 0, 0);
  if (next <= now) next.setDate(next.getDate() + 1);
  if (s.frequency === 'weekly' && s.day_of_week !== null) {
    while (next.getDay() !== s.day_of_week) next.setDate(next.getDate() + 1);
    return `${DAYS[s.day_of_week]}, ${next.toLocaleDateString([],{month:'short',day:'numeric'})} at ${next.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`;
  }
  return `${next.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})} at ${next.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`;
};

// ─── Toast ────────────────────────────────────────────────────────────────────
const Toast = ({ toasts }) => (
  <div className="fixed bottom-6 right-6 z-50 flex flex-col gap-2">
    {toasts.map(t => (
      <div key={t.id} className={`flex items-start gap-3 px-4 py-3 rounded-lg shadow-lg border text-sm max-w-xs animate-fade-in
        ${t.variant === 'destructive'
          ? 'bg-red-50 border-red-200 text-red-800'
          : 'bg-white border-gray-200 text-gray-800'}`}>
        {t.variant === 'destructive'
          ? <XCircle className="h-4 w-4 text-red-500 shrink-0 mt-0.5" />
          : <CheckCircle className="h-4 w-4 text-emerald-500 shrink-0 mt-0.5" />}
        <div>
          <p className="font-semibold">{t.title}</p>
          {t.description && <p className="text-xs opacity-75 mt-0.5">{t.description}</p>}
        </div>
      </div>
    ))}
  </div>
);

// ─── Modal ────────────────────────────────────────────────────────────────────
const Modal = ({ open, onClose, children }) => {
  if (!open) return null;
  return (
    <div className="fixed inset-0 z-40 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/20 backdrop-blur-sm" onClick={onClose} />
      <div className="relative bg-white border border-gray-200 rounded-xl shadow-2xl w-full max-w-md mx-4 p-6 z-10">
        {children}
      </div>
    </div>
  );
};

const AlertModal = ({ open, onClose, title, description, onConfirm, confirmLabel, confirmClass, loading }) => {
  if (!open) return null;
  return (
    <div className="fixed inset-0 z-40 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/20 backdrop-blur-sm" />
      <div className="relative bg-white border border-gray-200 rounded-xl shadow-2xl w-full max-w-sm mx-4 p-6 z-10">
        <h3 className="text-base font-semibold text-gray-900 mb-2">{title}</h3>
        <p className="text-sm text-gray-600 mb-6">{description}</p>
        <div className="flex gap-3 justify-end">
          <button onClick={onClose} disabled={loading}
            className="px-4 py-2 text-sm rounded-lg border border-gray-300 text-gray-700 hover:bg-gray-50 transition-colors disabled:opacity-50">
            Cancel
          </button>
          <button onClick={onConfirm} disabled={loading}
            className={`px-4 py-2 text-sm rounded-lg font-medium text-white transition-colors disabled:opacity-50 ${confirmClass}`}>
            {loading ? 'Working...' : confirmLabel}
          </button>
        </div>
      </div>
    </div>
  );
};

// ─── Main Component ───────────────────────────────────────────────────────────
export default function BackupRecovery() {
  const [backups, setBackups] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isRunning, setIsRunning] = useState(false);
  const [toasts, setToasts] = useState([]);

  const [restoreDialogOpen, setRestoreDialogOpen] = useState(false);
  const [restoreFile, setRestoreFile] = useState(null);
  const [isRestoring, setIsRestoring] = useState(false);

  const [backupDialogOpen, setBackupDialogOpen] = useState(false);
  const [selectedDbType, setSelectedDbType] = useState('postgresql');

  const [restoreFromFilename, setRestoreFromFilename] = useState(null);
  const [isRestoringFromFile, setIsRestoringFromFile] = useState(false);

  const [scheduleDialogOpen, setScheduleDialogOpen] = useState(false);
  const [isSavingSchedule, setIsSavingSchedule] = useState(false);
  const [schedule, setSchedule] = useState({
    enabled: true,
    frequency: 'daily',
    time: '02:00',
    day_of_week: 1,
  });

  // ── Toast helper ──
  const addToast = (toast) => {
    const id = Date.now();
    setToasts(prev => [...prev, { ...toast, id }]);
    setTimeout(() => setToasts(prev => prev.filter(t => t.id !== id)), 4000);
  };

  // ── Load fake data ──
  const loadData = useCallback(() => {
    setIsLoading(true);
    setTimeout(() => {
      setBackups(FAKE_BACKUPS);
      setIsLoading(false);
    }, 600);
  }, []);

  useEffect(() => { loadData(); }, [loadData]);

  // ── Download backup ──
  const downloadBackup = (backup) => {
    const sql = generateFakeSql(backup.filename);
    const blob = new Blob([sql], { type: 'application/sql' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = backup.filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
    addToast({ title: 'Download started', description: backup.filename });
  };

  // ── Trigger manual backup ──
  const triggerBackup = () => {
    setIsRunning(true);
    setBackupDialogOpen(false);
    const now = new Date();
    const pad = (n) => String(n).padStart(2, '0');
    const ts = `${now.getFullYear()}_${pad(now.getMonth()+1)}_${pad(now.getDate())}_${pad(now.getHours())}_${pad(now.getMinutes())}_${pad(now.getSeconds())}`;
    const filename = `backup_${ts}.sql`;

    const temp = {
      id: Date.now(),
      filename,
      size: 'Calculating...',
      created_at: now.toISOString().replace('T',' ').slice(0,19),
      status: 'in_progress',
      db_type: selectedDbType,
    };
    setBackups(prev => [temp, ...prev]);

    setTimeout(() => {
      setBackups(prev => prev.map(b =>
        b.id === temp.id ? { ...b, size: '14,421 KB', status: 'completed' } : b
      ));
      setIsRunning(false);
      addToast({ title: 'Backup Complete', description: `${filename} saved successfully` });
    }, 2200);
  };

  // ── Restore via upload ──
  const handleRestoreUpload = () => {
    if (!restoreFile) return;
    setIsRestoring(true);
    setTimeout(() => {
      setIsRestoring(false);
      setRestoreDialogOpen(false);
      setRestoreFile(null);
      addToast({ title: 'Import Successful', description: `${restoreFile.name} restored to PostgreSQL` });
    }, 1800);
  };

  // ── Restore from existing file ──
  const handleRestoreFromFile = () => {
    setIsRestoringFromFile(true);
    setTimeout(() => {
      setIsRestoringFromFile(false);
      setRestoreFromFilename(null);
      addToast({ title: 'Restore Complete', description: `Restored from ${restoreFromFilename}` });
    }, 1600);
  };

  // ── Delete backup ──
  const deleteBackup = (id) => {
    setBackups(prev => prev.filter(b => b.id !== id));
    addToast({ title: 'Backup deleted', description: 'Backup removed from history' });
  };

  // ── Save schedule ──
  const saveSchedule = () => {
    setIsSavingSchedule(true);
    setTimeout(() => {
      setIsSavingSchedule(false);
      setScheduleDialogOpen(false);
      addToast({ title: 'Schedule saved', description: 'Auto backup schedule updated' });
    }, 900);
  };

  return (
    <Layout>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Sans:wght@400;500;600&display=swap');
        * { box-sizing: border-box; }
        .font-mono { font-family: 'IBM Plex Mono', monospace; }
        .font-sans { font-family: 'IBM Plex Sans', sans-serif; }
        @keyframes fade-in { from { opacity:0; transform:translateY(8px) } to { opacity:1; transform:translateY(0) } }
        .animate-fade-in { animation: fade-in 0.25s ease both; }
        @keyframes spin { to { transform:rotate(360deg) } }
        .animate-spin { animation: spin 1s linear infinite; }
        ::-webkit-scrollbar { width: 6px; height: 6px; }
        ::-webkit-scrollbar-track { background: #f1f1f1; }
        ::-webkit-scrollbar-thumb { background: #c1c1c1; border-radius: 3px; }
        ::-webkit-scrollbar-thumb:hover { background: #a8a8a8; }
      `}</style>

      <div className="font-sans" style={{ minHeight:'100vh', background:'#f5f7fb', color:'#1f2937' }}>
        <Toast toasts={toasts} />

        <div style={{ maxWidth:1200, margin:'0 auto', padding:'2rem 1.5rem' }}>

          {/* Header */}
          <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:'2rem' }}>
            <div>
              <h1 style={{ fontSize:'1.5rem', fontWeight:600, color:'#111827', margin:0, letterSpacing:'-0.02em' }}>
                Backup & Recovery
              </h1>
              <p style={{ fontSize:'0.8125rem', color:'#6b7280', marginTop:4 }}>
                PostgreSQL · Automated daily dumps
              </p>
            </div>
            <button onClick={loadData}
              style={{ display:'flex', alignItems:'center', gap:6, padding:'0.5rem 1rem', background:'white',
                border:'1px solid #e5e7eb', borderRadius:8, color:'#4b5563', fontSize:'0.8125rem', cursor:'pointer' }}
              onMouseEnter={e=>e.currentTarget.style.background='#f9fafb'}
              onMouseLeave={e=>e.currentTarget.style.background='white'}>
              <RefreshCw size={14} /> Refresh
            </button>
          </div>

          {/* Quick Actions */}
          <div style={{ display:'grid', gridTemplateColumns:'repeat(3,1fr)', gap:'1rem', marginBottom:'1.5rem' }}>
            {[
              {
                icon: <FileArchive size={26} style={{color:'#3b82f6'}} />,
                title: 'Database Backup',
                desc: 'Full pg_dump saved to local storage',
                action: () => setBackupDialogOpen(true),
                badge: isRunning ? 'Running...' : 'Run Now',
                badgeColor: '#3b82f6',
                disabled: isRunning,
              },
              {
                icon: <Database size={26} style={{color:'#10b981'}} />,
                title: 'Import Database',
                desc: 'Upload a .sql file to restore',
                action: () => setRestoreDialogOpen(true),
                badge: 'Upload',
                badgeColor: '#10b981',
                disabled: false,
              },
              {
                icon: <Calendar size={26} style={{color:'#8b5cf6'}} />,
                title: 'Auto Schedule',
                desc: schedule.enabled
                  ? `${schedule.frequency.charAt(0).toUpperCase()+schedule.frequency.slice(1)} at ${schedule.time}`
                  : 'Scheduled backups are off',
                action: () => setScheduleDialogOpen(true),
                badge: 'Configure',
                badgeColor: schedule.enabled ? '#10b981' : '#9ca3af',
                disabled: false,
              },
            ].map((card, i) => (
              <button key={i} onClick={card.action} disabled={card.disabled}
                style={{ background:'white', border:'1px solid #e5e7eb', borderRadius:12,
                  padding:'1.25rem', textAlign:'left', cursor: card.disabled ? 'not-allowed' : 'pointer',
                  opacity: card.disabled ? 0.6 : 1, transition:'all 0.15s', boxShadow:'0 1px 2px rgba(0,0,0,0.05)' }}
                onMouseEnter={e => { if (!card.disabled) { e.currentTarget.style.borderColor='#d1d5db'; e.currentTarget.style.boxShadow='0 4px 6px -1px rgba(0,0,0,0.1)'; } }}
                onMouseLeave={e => { e.currentTarget.style.borderColor='#e5e7eb'; e.currentTarget.style.boxShadow='0 1px 2px rgba(0,0,0,0.05)'; }}>
                <div style={{ marginBottom:12 }}>{card.icon}</div>
                <p style={{ margin:'0 0 4px', fontSize:'0.875rem', fontWeight:500, color:'#111827' }}>{card.title}</p>
                <p style={{ margin:'0 0 12px', fontSize:'0.75rem', color:'#6b7280' }}>{card.desc}</p>
                <span style={{ fontSize:'0.75rem', fontWeight:500, color: card.badgeColor, display:'flex', alignItems:'center', gap:4 }}>
                  <Settings size={11} /> {card.badge}
                </span>
              </button>
            ))}
          </div>

          {/* Table */}
          <div style={{ background:'white', border:'1px solid #e5e7eb', borderRadius:12, overflow:'hidden', boxShadow:'0 1px 2px rgba(0,0,0,0.05)' }}>
            <div style={{ padding:'0.875rem 1.25rem', borderBottom:'1px solid #e5e7eb', display:'flex', alignItems:'center', justifyContent:'space-between' }}>
              <h2 style={{ margin:0, fontSize:'0.875rem', fontWeight:500, color:'#111827' }}>Backup History</h2>
              <span className="font-mono" style={{ fontSize:'0.6875rem', color:'#6b7280', padding:'2px 8px',
                background:'#f3f4f6', borderRadius:6 }}>{backups.length} records</span>
            </div>

            {isLoading ? (
              <div style={{ display:'flex', justifyContent:'center', alignItems:'center', padding:'5rem 0' }}>
                <div style={{ width:28, height:28, border:'2px solid #e5e7eb', borderTop:'2px solid #3b82f6', borderRadius:'50%' }}
                  className="animate-spin" />
              </div>
            ) : (
              <div style={{ overflowX:'auto' }}>
                <table style={{ width:'100%', borderCollapse:'collapse' }}>
                  <thead>
                    <tr style={{ background:'#f9fafb' }}>
                      {['Filename','DB Type','Size','Date','Status','Actions'].map(h => (
                        <th key={h} style={{ textAlign:'left', padding:'0.625rem 1rem', fontSize:'0.6875rem',
                          fontWeight:600, color:'#6b7280', textTransform:'uppercase', letterSpacing:'0.08em',
                          borderBottom:'1px solid #e5e7eb', whiteSpace:'nowrap' }}>{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {backups.length ? backups.map(b => {
                      const tc = dbTypeConfig[b.db_type ?? 'postgresql'];
                      return (
                        <tr key={b.id} style={{ borderBottom:'1px solid #f3f4f6', transition:'background 0.1s' }}
                          onMouseEnter={e=>e.currentTarget.style.background='#f9fafb'}
                          onMouseLeave={e=>e.currentTarget.style.background='transparent'}>

                          <td style={{ padding:'0.75rem 1rem' }}>
                            <span className="font-mono" style={{ fontSize:'0.8125rem', color:'#374151' }}>{b.filename}</span>
                          </td>

                          <td style={{ padding:'0.75rem 1rem' }}>
                            <span style={{ display:'inline-flex', alignItems:'center', gap:5, padding:'2px 10px',
                              borderRadius:9999, fontSize:'0.6875rem', fontWeight:500,
                              background:'#eff6ff', color:'#1d4ed8', border:'1px solid #bfdbfe' }}>
                              <Database size={10} /> {tc.label}
                            </span>
                          </td>

                          <td style={{ padding:'0.75rem 1rem' }}>
                            <span className="font-mono" style={{ fontSize:'0.8125rem', color:'#6b7280' }}>{b.size}</span>
                          </td>

                          <td style={{ padding:'0.75rem 1rem' }}>
                            <span style={{ display:'flex', alignItems:'center', gap:5, fontSize:'0.8125rem', color:'#6b7280' }}>
                              <Clock size={12} /> {b.created_at}
                            </span>
                          </td>

                          <td style={{ padding:'0.75rem 1rem' }}>
                            {b.status === 'completed' && (
                              <span style={{ display:'inline-flex', alignItems:'center', gap:5, padding:'2px 10px',
                                borderRadius:9999, fontSize:'0.6875rem', fontWeight:500,
                                background:'#ecfdf5', color:'#059669', border:'1px solid #a7f3d0' }}>
                                <CheckCircle size={10} /> Completed
                              </span>
                            )}
                            {b.status === 'in_progress' && (
                              <span style={{ display:'inline-flex', alignItems:'center', gap:5, padding:'2px 10px',
                                borderRadius:9999, fontSize:'0.6875rem', fontWeight:500,
                                background:'#eff6ff', color:'#2563eb', border:'1px solid #bfdbfe' }}>
                                <Loader size={10} className="animate-spin" /> In Progress
                              </span>
                            )}
                            {b.status === 'failed' && (
                              <span style={{ display:'inline-flex', alignItems:'center', gap:5, padding:'2px 10px',
                                borderRadius:9999, fontSize:'0.6875rem', fontWeight:500,
                                background:'#fef2f2', color:'#dc2626', border:'1px solid #fecaca' }}>
                                <XCircle size={10} /> Failed
                              </span>
                            )}
                          </td>

                          <td style={{ padding:'0.75rem 1rem' }}>
                            <div style={{ display:'flex', gap:4 }}>
                              {[
                                { icon:<Download size={14}/>, title:'Download', color:'#6b7280', hoverColor:'#3b82f6',
                                  onClick:()=>downloadBackup(b), disabled: b.status!=='completed' },
                                { icon:<RotateCcw size={14}/>, title:'Restore', color:'#6b7280', hoverColor:'#f59e0b',
                                  onClick:()=>setRestoreFromFilename(b.filename), disabled: b.status!=='completed' },
                                { icon:<Trash2 size={14}/>, title:'Delete', color:'#6b7280', hoverColor:'#ef4444',
                                  onClick:()=>deleteBackup(b.id), disabled: b.status==='in_progress' },
                              ].map((btn, i) => (
                                <button key={i} title={btn.title} onClick={btn.onClick} disabled={btn.disabled}
                                  style={{ width:30, height:30, display:'flex', alignItems:'center', justifyContent:'center',
                                    background:'white', border:'1px solid #e5e7eb', borderRadius:6,
                                    color: btn.color, cursor: btn.disabled ? 'not-allowed' : 'pointer',
                                    opacity: btn.disabled ? 0.3 : 1, transition:'all 0.15s' }}
                                  onMouseEnter={e => { if (!btn.disabled) { e.currentTarget.style.color=btn.hoverColor; e.currentTarget.style.borderColor=btn.hoverColor; e.currentTarget.style.background='#f9fafb'; } }}
                                  onMouseLeave={e => { e.currentTarget.style.color=btn.color; e.currentTarget.style.borderColor='#e5e7eb'; e.currentTarget.style.background='white'; }}>
                                  {btn.icon}
                                </button>
                              ))}
                            </div>
                          </td>
                        </tr>
                      );
                    }) : (
                      <tr><td colSpan={6} style={{ padding:'4rem', textAlign:'center', color:'#6b7280', fontSize:'0.875rem' }}>
                        No backups found
                      </td></tr>
                    )}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>

        {/* ── BACKUP DIALOG ── */}
        <Modal open={backupDialogOpen} onClose={() => !isRunning && setBackupDialogOpen(false)}>
          <h3 style={{ margin:'0 0 6px', fontSize:'1rem', fontWeight:600, color:'#111827' }}>Create Database Backup</h3>
          <p style={{ margin:'0 0 20px', fontSize:'0.8125rem', color:'#6b7280' }}>
            Runs <code style={{color:'#3b82f6'}}>pg_dump</code> and saves a full <code style={{color:'#3b82f6'}}>.sql</code> file.
          </p>
          <div style={{ marginBottom:16 }}>
            <label style={{ display:'block', fontSize:'0.75rem', fontWeight:500, color:'#374151', marginBottom:6 }}>Database Type</label>
            <select value={selectedDbType} onChange={e=>setSelectedDbType(e.target.value)}
              style={{ width:'100%', padding:'0.5rem 0.75rem', background:'white', border:'1px solid #d1d5db',
                borderRadius:8, color:'#111827', fontSize:'0.875rem', cursor:'pointer' }}>
              <option value="postgresql">PostgreSQL</option>
              <option value="mysql">MySQL</option>
              <option value="sqlite">SQLite</option>
            </select>
          </div>
          <div style={{ padding:'0.75rem 1rem', borderRadius:8, marginBottom:20,
            background: selectedDbType==='postgresql' ? '#eff6ff' : selectedDbType==='mysql' ? '#fff7ed' : '#ecfdf5',
            border: `1px solid ${selectedDbType==='postgresql'?'#bfdbfe':selectedDbType==='mysql'?'#fed7aa':'#a7f3d0'}` }}>
            <p style={{ margin:0, fontSize:'0.8125rem', color: selectedDbType==='postgresql'?'#1e40af':selectedDbType==='mysql'?'#9a3412':'#065f46' }}>
              {selectedDbType==='postgresql' && 'Uses pg_dump to export a plain SQL file.'}
              {selectedDbType==='mysql' && 'Uses mysqldump --quick --single-transaction (no locks).'}
              {selectedDbType==='sqlite' && 'Copies the .sqlite database file directly.'}
            </p>
          </div>
          <div style={{ display:'flex', gap:8, justifyContent:'flex-end' }}>
            <button onClick={()=>setBackupDialogOpen(false)} disabled={isRunning}
              style={{ padding:'0.5rem 1rem', background:'white', border:'1px solid #d1d5db', borderRadius:8,
                color:'#374151', fontSize:'0.875rem', cursor:'pointer' }}>Cancel</button>
            <button onClick={triggerBackup} disabled={isRunning}
              style={{ display:'flex', alignItems:'center', gap:6, padding:'0.5rem 1rem', background:'#3b82f6',
                border:'none', borderRadius:8, color:'white', fontSize:'0.875rem', cursor:'pointer', fontWeight:500 }}>
              <Play size={14} /> {isRunning ? 'Running...' : 'Start Backup'}
            </button>
          </div>
        </Modal>

        {/* ── IMPORT DIALOG ── */}
        <Modal open={restoreDialogOpen} onClose={() => { if (!isRestoring) { setRestoreDialogOpen(false); setRestoreFile(null); } }}>
          <h3 style={{ margin:'0 0 6px', fontSize:'1rem', fontWeight:600, color:'#111827' }}>Import Database</h3>
          <p style={{ margin:'0 0 20px', fontSize:'0.8125rem', color:'#6b7280' }}>
            Upload a <code style={{color:'#3b82f6'}}>.sql</code> file to restore into PostgreSQL. This will overwrite existing data.
          </p>
          <div style={{ marginBottom: restoreFile ? 12 : 20 }}>
            <label style={{ display:'block', fontSize:'0.75rem', fontWeight:500, color:'#374151', marginBottom:8 }}>SQL File</label>
            <input type="file" accept=".sql" onChange={e=>setRestoreFile(e.target.files?.[0]??null)}
              style={{ display:'block', width:'100%', fontSize:'0.8125rem', color:'#374151',
                padding:'0.5rem', background:'white', border:'1px solid #d1d5db', borderRadius:8, cursor:'pointer' }} />
          </div>
          {restoreFile && (
            <div style={{ padding:'0.625rem 0.875rem', background:'#ecfdf5', border:'1px solid #a7f3d0',
              borderRadius:8, marginBottom:20, fontSize:'0.75rem', color:'#065f46' }}>
              ✓ {restoreFile.name} ({(restoreFile.size/1024).toFixed(1)} KB) — ready to import into PostgreSQL
            </div>
          )}
          <div style={{ display:'flex', gap:8, justifyContent:'flex-end' }}>
            <button onClick={()=>{ setRestoreDialogOpen(false); setRestoreFile(null); }} disabled={isRestoring}
              style={{ padding:'0.5rem 1rem', background:'white', border:'1px solid #d1d5db', borderRadius:8,
                color:'#374151', fontSize:'0.875rem', cursor:'pointer' }}>Cancel</button>
            <button onClick={handleRestoreUpload} disabled={!restoreFile||isRestoring}
              style={{ padding:'0.5rem 1rem', background: (!restoreFile||isRestoring)?'#d1d5db':'#10b981',
                border:'none', borderRadius:8, color:'white', fontSize:'0.875rem', fontWeight:500,
                cursor: (!restoreFile||isRestoring)?'not-allowed':'pointer' }}>
              {isRestoring ? 'Importing...' : 'Import'}
            </button>
          </div>
        </Modal>

        {/* ── SCHEDULE DIALOG ── */}
        <Modal open={scheduleDialogOpen} onClose={() => !isSavingSchedule && setScheduleDialogOpen(false)}>
          <h3 style={{ margin:'0 0 6px', fontSize:'1rem', fontWeight:600, color:'#111827' }}>Auto Backup Schedule</h3>
          <p style={{ margin:'0 0 20px', fontSize:'0.8125rem', color:'#6b7280' }}>Configure when automatic backups run.</p>
          <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:20,
            padding:'0.75rem 1rem', background:'#f9fafb', borderRadius:8 }}>
            <div>
              <p style={{ margin:0, fontSize:'0.875rem', fontWeight:500, color:'#111827' }}>Enable auto backup</p>
              <p style={{ margin:'2px 0 0', fontSize:'0.75rem', color:'#6b7280' }}>Run backups automatically</p>
            </div>
            <button onClick={()=>setSchedule(s=>({...s,enabled:!s.enabled}))}
              style={{ width:44, height:24, borderRadius:12, border:'none', cursor:'pointer', position:'relative',
                background: schedule.enabled ? '#3b82f6' : '#d1d5db', transition:'background 0.2s' }}>
              <div style={{ position:'absolute', top:2, left: schedule.enabled?22:2, width:20, height:20,
                borderRadius:'50%', background:'white', transition:'left 0.2s' }} />
            </button>
          </div>

          <div style={{ opacity: schedule.enabled ? 1 : 0.4, pointerEvents: schedule.enabled ? 'all' : 'none', transition:'opacity 0.2s' }}>
            <div style={{ marginBottom:16 }}>
              <label style={{ display:'block', fontSize:'0.75rem', fontWeight:500, color:'#374151', marginBottom:6 }}>Frequency</label>
              <select value={schedule.frequency} onChange={e=>setSchedule(s=>({...s,frequency:e.target.value}))}
                style={{ width:'100%', padding:'0.5rem 0.75rem', background:'white', border:'1px solid #d1d5db',
                  borderRadius:8, color:'#111827', fontSize:'0.875rem' }}>
                <option value="hourly">Every hour</option>
                <option value="daily">Daily</option>
                <option value="weekly">Weekly</option>
              </select>
            </div>

            {schedule.frequency !== 'hourly' && (
              <div style={{ marginBottom:16 }}>
                <label style={{ display:'block', fontSize:'0.75rem', fontWeight:500, color:'#374151', marginBottom:6 }}>Time</label>
                <input type="time" value={schedule.time} onChange={e=>setSchedule(s=>({...s,time:e.target.value}))}
                  style={{ width:'100%', padding:'0.5rem 0.75rem', background:'white', border:'1px solid #d1d5db',
                    borderRadius:8, color:'#111827', fontSize:'0.875rem' }} />
              </div>
            )}

            {schedule.frequency === 'weekly' && (
              <div style={{ marginBottom:16 }}>
                <label style={{ display:'block', fontSize:'0.75rem', fontWeight:500, color:'#374151', marginBottom:8 }}>Day of week</label>
                <div style={{ display:'flex', gap:6, flexWrap:'wrap' }}>
                  {DAYS_SHORT.map((day,i) => (
                    <button key={i} onClick={()=>setSchedule(s=>({...s,day_of_week:i}))}
                      style={{ padding:'4px 10px', borderRadius:6, fontSize:'0.75rem', fontWeight:500, cursor:'pointer',
                        border: schedule.day_of_week===i ? '1px solid #3b82f6' : '1px solid #d1d5db',
                        background: schedule.day_of_week===i ? '#3b82f6' : 'white',
                        color: schedule.day_of_week===i ? 'white' : '#374151', transition:'all 0.15s' }}>
                      {day}
                    </button>
                  ))}
                </div>
              </div>
            )}

            <div style={{ padding:'0.75rem 1rem', background:'#f9fafb', border:'1px solid #e5e7eb', borderRadius:8, marginBottom:20 }}>
              <p style={{ margin:'0 0 2px', fontSize:'0.6875rem', color:'#6b7280' }}>Next scheduled run</p>
              <p style={{ margin:0, fontSize:'0.875rem', fontWeight:500, color:'#111827' }}>{getNextRunText(schedule)}</p>
            </div>
          </div>

          <div style={{ display:'flex', gap:8, justifyContent:'flex-end' }}>
            <button onClick={()=>setScheduleDialogOpen(false)} disabled={isSavingSchedule}
              style={{ padding:'0.5rem 1rem', background:'white', border:'1px solid #d1d5db', borderRadius:8,
                color:'#374151', fontSize:'0.875rem', cursor:'pointer' }}>Cancel</button>
            <button onClick={saveSchedule} disabled={isSavingSchedule}
              style={{ padding:'0.5rem 1rem', background:'#3b82f6', border:'none', borderRadius:8,
                color:'white', fontSize:'0.875rem', fontWeight:500, cursor:'pointer' }}>
              {isSavingSchedule ? 'Saving...' : 'Save Schedule'}
            </button>
          </div>
        </Modal>

        {/* ── RESTORE CONFIRMATION ── */}
        <AlertModal
          open={!!restoreFromFilename}
          onClose={() => !isRestoringFromFile && setRestoreFromFilename(null)}
          title="Restore from Backup"
          description={`This will restore the PostgreSQL database from ${restoreFromFilename}. All current data will be overwritten. Are you sure?`}
          onConfirm={handleRestoreFromFile}
          confirmLabel="Yes, Restore"
          confirmClass="bg-amber-500 hover:bg-amber-600"
          loading={isRestoringFromFile}
        />
      </div>
    </Layout>
  );
}